# Generated by Django 5.2 on 2025-05-05 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0002_recipe_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_mealplans', to=settings.AUTH_USER_MODEL),
        ),
    ]
