# Generated by Django 5.2 on 2025-05-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0003_mealplan_saved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mealplans/'),
        ),
    ]
