# Generated by Django 4.2.10 on 2024-05-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_author_article_header_image_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
